#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"

source .env

su "${REMOTE_SERVER_USER}" <<EOF
#!/bin/bash
. ~/.nvm/nvm.sh
nvm use 18
NODE_ENV=production npm run start:prod
EOF
