FROM node:18-alpine

RUN apk add --no-cache bash

WORKDIR /usr/app

COPY ../.env ./
COPY ../version ./
COPY ../package*.json ./
COPY ../dist/ ./dist
COPY ../static.generated/ ./static.generated

RUN npm install --omit=dev


RUN cat > ./start-server <<EOL
#!/bin/bash
npm run start:dev
EOL


RUN chmod +x ./start-server

EXPOSE 3336

# just start & we'll run it manually
ENTRYPOINT ["sleep", "infinity"]