#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}/../"

project_root="$(pwd)"

"${project_root}/scripts.dev/cmd-fe-copy-static-files"
"${project_root}/scripts.dev/homepage-fe-copy-static-files"
