#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}/../"

export STATIC_PATH_GENERATED="$(pwd)/static.generated"

fe_module="$(pwd)/src/common_modules/cmd-explorer/cmd-fe.alone"
fe_module_static_path="${fe_module}/dist/static"
fe_module_build="./setup-prod"
fe_static_path="${STATIC_PATH_GENERATED}/cmd-fe.alone"

rm -r "${fe_static_path}"

# build homepage fe
cd "${fe_module}" && ./setup-init && "${fe_module_build}" && cd - && \
mkdir -p "${fe_static_path}" && \
cp -r "${fe_module_static_path}" "${fe_static_path}"
