#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}/../"

source .env
export VERSION="$(cat version)"

# build production version of application
# ./setup-prod
. ~/.nvm/nvm.sh
nvm use 18
npm run setup:prod:docker

export DOCKERFILE="./scripts.prod/Dockerfile.prod"
# build docker image
docker compose build

image="${DOCKER_IMAGE_NAME}:${VERSION}"
tag_name="${DOCKER_HUB_USER}/${DOCKER_IMAGE_NAME}:${VERSION}"

# tag the image - this will be the name of image from docker hub
docker tag "${image}" "${tag_name}"

docker image ls "${DOCKER_IMAGE_NAME}*"
