#!/bin/env bash

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.nvm/nvm.sh

nvm install 18
node --version

sudo apt update
sudo apt install network-manager -y



